# On part d'Ubuntu
FROM ubuntu:latest

# Mise à jour de la liste des logiciels
RUN apt-get update

# Mise à jour de tous les logiciels installés
RUN apt-get upgrade -y

# Quand on lance le conteneur, il affiche "Hello, World!"
CMD echo "Hello, World!"
