version: '3'

services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile-back
    image: softy-pinko-back-end:task5

  front-end:
    build:
      context: .
      dockerfile: Dockerfile-front
    image: softy-pinko-front-end:task5
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end